In [1]:
from google.colab import drive
drive.mount("/content/drive")

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive

1. Read the dataset
2. Drop the columns which are unique for all users like IDs (5 points)
3. Distinguish the feature and target set (5 points)
4. Divide the data set into Train and test sets
5. Normalize the train and test data (5 points)
6. Initialize & build the model (10 points)
7. Optimize the model (Optional)
8. Predict the results using 0.5 as a threshold (Optional)
Print the Accuracy score and confusion matrix (5 points)

In [0]:
import numpy as np
import pandas as pd

In [0]:
bank_df = pd.read_csv("/content/drive/My Drive/AIML/bank.csv")

In [5]:
bank_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
RowNumber          10000 non-null int64
CustomerId         10000 non-null int64
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [0]:
# drop unique values from data set
bank_df = bank_df.drop(columns = ['RowNumber','CustomerId','Surname'],axis =1)

In [7]:
bank_df.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1
3          699    France  Female  ...               0         93826.63       0
4          850     Spain  Female  ...               1         79084.10       0

[5 rows x 11 columns]

In [0]:
bank_df =  pd.get_dummies(bank_df,drop_first=True)

In [0]:
X = bank_df.drop(columns=['Exited'],axis=1)
y =  bank_df[['Exited']]

In [0]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 0)

In [13]:
X_train.head()

      CreditScore  Age  Tenure  ...  Geography_Germany  Geography_Spain  Gender_Male
7681          641   33       2  ...                  0                0            1
9031          541   39       7  ...                  0                0            1
3691          590   76       5  ...                  0                0            0
202           516   50       5  ...                  0                1            1
5625          508   60       7  ...                  0                0            0

[5 rows x 11 columns]

In [0]:
#feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [0]:
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [16]:
import keras
from keras.models import Sequential
from keras.layers import Dense,Dropout

Using TensorFlow backend.

In [17]:
#initialize ANN
classifier = Sequential()


#Adding Input layer and hidden layer
classifier.add(Dense(units= 8, kernel_initializer='uniform',activation='relu', input_dim= 11))
classifier.add(Dropout(0.3))

#Addeding Second hidden layer 
classifier.add(Dense(units=6,kernel_initializer='uniform', activation='relu'))
classifier.add(Dropout(0.5))

#adding output layer
classifier.add(Dense(units=1, kernel_initializer='uniform', activation='sigmoid'))

WARNING: Logging before flag parsing goes to stderr.
W0901 16:07:11.214199 140229296875392 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:66: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0901 16:07:11.276156 140229296875392 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:541: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0901 16:07:11.284095 140229296875392 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4432: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0901 16:07:11.310442 140229296875392 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:148: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.

W0901 16:07:11.321014 140229296875392 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3733: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.

In [18]:
classifier.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])

W0901 16:07:20.988189 140229296875392 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:793: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0901 16:07:21.020914 140229296875392 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3657: The name tf.log is deprecated. Please use tf.math.log instead.

W0901 16:07:21.027840 140229296875392 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

In [19]:
classifier.fit(X_train,y_train, batch_size=30, epochs= 100)

Epoch 1/100
7000/7000 [==============================] - 1s 146us/step - loss: 0.6028 - acc: 0.7971
Epoch 2/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4844 - acc: 0.7977
Epoch 3/100
7000/7000 [==============================] - 0s 40us/step - loss: 0.4743 - acc: 0.7977
Epoch 4/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4709 - acc: 0.7976
Epoch 5/100
7000/7000 [==============================] - 0s 42us/step - loss: 0.4655 - acc: 0.7993
Epoch 6/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4623 - acc: 0.8023
Epoch 7/100
7000/7000 [==============================] - 0s 42us/step - loss: 0.4609 - acc: 0.8031
Epoch 8/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4592 - acc: 0.8006
Epoch 9/100
7000/7000 [==============================] - 0s 40us/step - loss: 0.4597 - acc: 0.8044
Epoch 10/100
7000/7000 [==============================] - 0s 39us/step - loss: 0.4533 - acc: 0.8036
Epoch 11/100
7000/7000 [==============================] - 0s 42us/step - loss: 0.4515 - acc: 0.8080
Epoch 12/100
7000/7000 [==============================] - 0s 40us/step - loss: 0.4539 - acc: 0.8071
Epoch 13/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4569 - acc: 0.8034
Epoch 14/100
7000/7000 [==============================] - 0s 40us/step - loss: 0.4545 - acc: 0.8063
Epoch 15/100
7000/7000 [==============================] - 0s 40us/step - loss: 0.4498 - acc: 0.8061
Epoch 16/100
7000/7000 [==============================] - 0s 43us/step - loss: 0.4551 - acc: 0.8023
Epoch 17/100
7000/7000 [==============================] - 0s 45us/step - loss: 0.4445 - acc: 0.8087
Epoch 18/100
7000/7000 [==============================] - 0s 45us/step - loss: 0.4529 - acc: 0.8057
Epoch 19/100
7000/7000 [==============================] - 0s 42us/step - loss: 0.4468 - acc: 0.8080
Epoch 20/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4475 - acc: 0.8074
Epoch 21/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4497 - acc: 0.8087
Epoch 22/100
7000/7000 [==============================] - 0s 42us/step - loss: 0.4477 - acc: 0.8099
Epoch 23/100
7000/7000 [==============================] - 0s 40us/step - loss: 0.4461 - acc: 0.8086
Epoch 24/100
7000/7000 [==============================] - 0s 40us/step - loss: 0.4446 - acc: 0.8124
Epoch 25/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4427 - acc: 0.8101
Epoch 26/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4448 - acc: 0.8073
Epoch 27/100
7000/7000 [==============================] - 0s 40us/step - loss: 0.4415 - acc: 0.8081
Epoch 28/100
7000/7000 [==============================] - 0s 40us/step - loss: 0.4430 - acc: 0.8123
Epoch 29/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4445 - acc: 0.8079
Epoch 30/100
7000/7000 [==============================] - 0s 45us/step - loss: 0.4416 - acc: 0.8111
Epoch 31/100
7000/7000 [==============================] - 0s 42us/step - loss: 0.4461 - acc: 0.8059
Epoch 32/100
7000/7000 [==============================] - 0s 40us/step - loss: 0.4433 - acc: 0.8083
Epoch 33/100
7000/7000 [==============================] - 0s 40us/step - loss: 0.4408 - acc: 0.8093
Epoch 34/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4402 - acc: 0.8117
Epoch 35/100
7000/7000 [==============================] - 0s 40us/step - loss: 0.4356 - acc: 0.8111
Epoch 36/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4397 - acc: 0.8099
Epoch 37/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4410 - acc: 0.8094
Epoch 38/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4342 - acc: 0.8109
Epoch 39/100
7000/7000 [==============================] - 0s 42us/step - loss: 0.4403 - acc: 0.8091
Epoch 40/100
7000/7000 [==============================] - 0s 40us/step - loss: 0.4401 - acc: 0.8099
Epoch 41/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4406 - acc: 0.8084
Epoch 42/100
7000/7000 [==============================] - 0s 43us/step - loss: 0.4427 - acc: 0.8076
Epoch 43/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4328 - acc: 0.8104
Epoch 44/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4397 - acc: 0.8107
Epoch 45/100
7000/7000 [==============================] - 0s 40us/step - loss: 0.4381 - acc: 0.8064
Epoch 46/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4333 - acc: 0.8091
Epoch 47/100
7000/7000 [==============================] - 0s 40us/step - loss: 0.4384 - acc: 0.8099
Epoch 48/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4429 - acc: 0.8066
Epoch 49/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4390 - acc: 0.8056
Epoch 50/100
7000/7000 [==============================] - 0s 43us/step - loss: 0.4383 - acc: 0.8093
Epoch 51/100
7000/7000 [==============================] - 0s 40us/step - loss: 0.4381 - acc: 0.8061
Epoch 52/100
7000/7000 [==============================] - 0s 40us/step - loss: 0.4411 - acc: 0.8127
Epoch 53/100
7000/7000 [==============================] - 0s 40us/step - loss: 0.4411 - acc: 0.8073
Epoch 54/100
7000/7000 [==============================] - 0s 40us/step - loss: 0.4385 - acc: 0.8054
Epoch 55/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4356 - acc: 0.8113
Epoch 56/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4399 - acc: 0.8057
Epoch 57/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4387 - acc: 0.8103
Epoch 58/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4443 - acc: 0.8090
Epoch 59/100
7000/7000 [==============================] - 0s 40us/step - loss: 0.4390 - acc: 0.8106
Epoch 60/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4401 - acc: 0.8081
Epoch 61/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4362 - acc: 0.8091
Epoch 62/100
7000/7000 [==============================] - 0s 42us/step - loss: 0.4411 - acc: 0.8057
Epoch 63/100
7000/7000 [==============================] - 0s 40us/step - loss: 0.4354 - acc: 0.8113
Epoch 64/100
7000/7000 [==============================] - 0s 42us/step - loss: 0.4357 - acc: 0.8120
Epoch 65/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4419 - acc: 0.8100
Epoch 66/100
7000/7000 [==============================] - 0s 43us/step - loss: 0.4352 - acc: 0.8146
Epoch 67/100
7000/7000 [==============================] - 0s 43us/step - loss: 0.4389 - acc: 0.8133
Epoch 68/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4395 - acc: 0.8136
Epoch 69/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4354 - acc: 0.8133
Epoch 70/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4329 - acc: 0.8136
Epoch 71/100
7000/7000 [==============================] - 0s 40us/step - loss: 0.4389 - acc: 0.8130
Epoch 72/100
7000/7000 [==============================] - 0s 40us/step - loss: 0.4390 - acc: 0.8120
Epoch 73/100
7000/7000 [==============================] - 0s 40us/step - loss: 0.4397 - acc: 0.8140
Epoch 74/100
7000/7000 [==============================] - 0s 42us/step - loss: 0.4345 - acc: 0.8151
Epoch 75/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4402 - acc: 0.8129
Epoch 76/100
7000/7000 [==============================] - 0s 42us/step - loss: 0.4435 - acc: 0.8089
Epoch 77/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4367 - acc: 0.8171
Epoch 78/100
7000/7000 [==============================] - 0s 40us/step - loss: 0.4379 - acc: 0.8124
Epoch 79/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4351 - acc: 0.8166
Epoch 80/100
7000/7000 [==============================] - 0s 40us/step - loss: 0.4414 - acc: 0.8119
Epoch 81/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4380 - acc: 0.8134
Epoch 82/100
7000/7000 [==============================] - 0s 42us/step - loss: 0.4391 - acc: 0.8139
Epoch 83/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4391 - acc: 0.8129
Epoch 84/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4431 - acc: 0.8114
Epoch 85/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4390 - acc: 0.8127
Epoch 86/100
7000/7000 [==============================] - 0s 40us/step - loss: 0.4402 - acc: 0.8093
Epoch 87/100
7000/7000 [==============================] - 0s 40us/step - loss: 0.4357 - acc: 0.8150
Epoch 88/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4367 - acc: 0.8113
Epoch 89/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4365 - acc: 0.8136
Epoch 90/100
7000/7000 [==============================] - 0s 40us/step - loss: 0.4283 - acc: 0.8163
Epoch 91/100
7000/7000 [==============================] - 0s 40us/step - loss: 0.4341 - acc: 0.8184
Epoch 92/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4392 - acc: 0.8116
Epoch 93/100
7000/7000 [==============================] - 0s 42us/step - loss: 0.4375 - acc: 0.8117
Epoch 94/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4431 - acc: 0.8096
Epoch 95/100
7000/7000 [==============================] - 0s 43us/step - loss: 0.4445 - acc: 0.8080
Epoch 96/100
7000/7000 [==============================] - 0s 40us/step - loss: 0.4346 - acc: 0.8136
Epoch 97/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4386 - acc: 0.8140
Epoch 98/100
7000/7000 [==============================] - 0s 40us/step - loss: 0.4399 - acc: 0.8117
Epoch 99/100
7000/7000 [==============================] - 0s 42us/step - loss: 0.4317 - acc: 0.8166
Epoch 100/100
7000/7000 [==============================] - 0s 41us/step - loss: 0.4404 - acc: 0.8106

In [0]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [0]:
# making confusion matrix
from sklearn.metrics import confusion_matrix,accuracy_score
Confusion_Matrix = confusion_matrix(y_test, y_pred)
Accuracy = accuracy_score(y_test,y_pred)

In [25]:
Accuracy

0.8006666666666666

In [26]:
Confusion_Matrix

array([[2377,    2],
       [ 596,   25]])